package team34.tarot.utils;

import java.util.Arrays;
import java.util.Optional;

public class TarotCardSetSingleton {

	private static final TarotCardSetSingleton standard = new TarotCardSetSingleton();
	private TarotCard[] tarotCardSet;

	private TarotCardSetSingleton() {
		tarotCardSet = new TarotCard[16];

		tarotCardSet[0] = new TarotCard(0, "The Fool", "major",
						"화려한 의상을 입은 젊은 남성이 세상의 높은 곳에서 발걸음을 내디뎠다가 멈춰 서 있는 모습을 묘사합니다. 그는 다른 세계의 왕자로서 경험을 추구하는 영혼을 상징하며, 자유로운 사고와 영적인 성장을 나타냅니다. 이 카드는 새로운 경험과 지혜를 향한 열망을 상징하며, 현재의 순간에 대한 기대와 희망을 전달합니다.",
						"With light step, as if earth and its trammels had little power to restrain him, a young man in gorgeous vestments pauses at the brink of a precipice among the great heights of the world; he surveys the blue distance before him-its expanse of sky rather than the prospect below. His act of eager walking is still indicated, though he is stationary at the given moment; his dog is still bounding. The edge which opens on the depth has no terror; it is as if angels were waiting to uphold him, if it came about that he leaped from the height. His countenance is full of intelligence and expectant dream. He has a rose in one hand and in the other a costly wand, from which depends over his right shoulder a wallet curiously embroidered. He is a prince of the other world on his travels through this one-all amidst the morning glory, in the keen air. The sun, which shines behind him, knows whence he came, whither he is going, and how he will return by another path after many days. He is the spirit in search of experience. Many symbols of the Instituted Mysteries are summarized in this card, which reverses, under high warrants, all the confusions that have preceded it.\\nIn his Manual of Cartomancy, Grand Orient has a curious suggestion of the office of Mystic Fool, as apart of his process in higher divination; but it might call for more than ordinary gifts to put it into operation. We shall see how the card fares according to the common arts of fortune-telling, and it will be an example, to those who can discern, of the fact, otherwise so evident, that the Trumps Major had no place originally in the arts of psychic gambling, when cards are used as the counters and pretexts. Of the circumstances under which this art arose we know, however, very little. The conventional explanations say that the Fool signifies the flesh, the sensitive life, and by a peculiar satire its subsidiary name was at one time the alchemist, as depicting folly at the most insensate stage.");
		tarotCardSet[1] = new TarotCard(1, "The Magician", "major",
						"신성한 의지, 영적과 물질적 세계의 연결, 그리고 지속적인 정신적 성장을 상징합니다. 이 카드는 자기 신뢰와 초기의 행동, 창조적인 힘, 그리고 변화의 가능성을 나타냅니다. 그것은 또한 개인이 영혼의 힘과 선물을 가지고 있으며, 이들을 적절히 사용하여 세상에 영향을 미칠 수 있다는 메시지를 전달합니다.",
						"A youthful figure in the robe of a magician, having the countenance of divine Apollo, with smile of confidence and shining eyes. Above his head is the mysterious sign of the Holy Spirit, the sign of life, like an endless cord, forming the figure 8 in a horizontal position . About his waist is a serpent-cincture, the serpent appearing to devour its own tail. This is familiar to most as a conventional symbol of eternity, but here it indicates more especially the eternity of attainment in the spirit. In the Magician's right hand is a wand raised towards heaven, while the left hand is pointing to the earth. This dual sign is known in very high grades of the Instituted Mysteries; it shews the descent of grace, virtue and light, drawn from things above and derived to things below. The suggestion throughout is therefore the possession and communication of the Powers and Gifts of the Spirit. On the table in front of the Magician are the symbols of the four Tarot suits, signifying the elements of natural life, which lie like counters before the adept, and he adapts them as he wills. Beneath are roses and lilies, the flos campi and lilium convallium, changed into garden flowers, to shew the culture of aspiration. This card signifies the divine motive in man, reflecting God, the will in the liberation of its union with that which is above. It is also the unity of individual being on all planes, and in a very high sense it is thought, in the fixation thereof. With further reference to what I have called the sign of life and its connexion with the number 8, it may be remembered that Christian Gnosticism speaks of rebirth in Christ as a change \\\"unto the Ogdoad.\\\" The mystic number is termed Jerusalem above, the Land flowing with Milk and Honey, the Holy Spirit and the Land of the Lord. According to Martinism, 8 is the number of Christ.");
		tarotCardSet[2] = new TarotCard(3, "The Empress", "major",
						"왕자 같은 외모의 고상한 여성을 묘사합니다. 그녀는 천국과 지구의 딸로서 풍요와 창조성을 상징합니다. 열두 개의 별로 이루어진 관을 쓰고, 비너스의 상징이 있는 방패를 가지고 있습니다. 그녀 앞에는 익은 곡식이 펼쳐지고, 물이 흐르고 있습니다. 이 카드는 풍요와 성숙, 창의력과 인내력을 나타내며, 환경과의 조화를 상징합니다. 그녀는 모성적인 성질과 창조적인 에너지를 지닌 여성의 상징이며, 인간과 자연의 상호작용을 나타냅니다.",
						"A stately figure, seated, having rich vestments and royal aspect, as of a daughter of heaven and earth. Her diadem is of twelve stars, gathered in a cluster. The symbol of Venus is on the shield which rests near her. A field of corn is ripening in front of her, and beyond there is a fall of water. The sceptre which she bears is surmounted by the globe of this world. She is the inferior Garden of Eden, the Earthly Paradise, all that is symbolized by the visible house of man. She is not Regina coeli, but she is still refugium peccatorum, the fruitful mother of thousands. There are also certain aspects in which she has been correctly described as desire and the wings thereof, as the woman clothed with the sun, as Gloria Mundi and the veil of the Sanctum Sanctorum; but she is not, I may add, the soul that has attained wings, unless all the symbolism is counted up another and unusual way. She is above all things universal fecundity and the outer sense of the Word. This is obvious, because there is no direct message which has been given to man like that which is borne by woman; but she does not herself carry its interpretation.\\nIn another order of ideas, the card of the Empress signifies the door or gate by which an entrance is obtained into this life, as into the Garden of Venus; and then the way which leads out therefrom, into that which is beyond, is the secret known to the High Priestess: it is communicated by her to the elect. Most old attributions of this card are completely wrong on the symbolism--as, for example, its identification with the Word, Divine Nature, the Triad, and so forth.");
		tarotCardSet[3] = new TarotCard(11, "Justice", "major",
						"도덕적 원리와 보답을 상징합니다. 인물이 기둥 사이에 앉아 있는 모습은 대제사장과 유사합니다. 이 카드는 선출과는 다른 영적 정의를 나타내며, 헌신과 영감에 대한 신비한 예비지식을 갖고 있습니다. 선물과 영감은 존재할 수도, 부재할 수도 있으며, 그 존재는 신비로운 것입니다. \"정의\"의 기둥은 한 세계로 향하고 대제사장의 기둥은 다른 세계로 향합니다.",
						"As this card follows the traditional symbolism and carries above all its obvious meanings, there is little to say regarding it outside the few considerations collected in the first part, to which the reader is referred.\\nIt will be seen, however, that the figure is seated between pillars, like the High Priestess, and on this account it seems desirable to indicate that the moral principle which deals unto every man according to his works--while, of course, it is in strict analogy with higher things;--differs in its essence from the spiritual justice which is involved in the idea of election. The latter belongs to a mysterious order of Providence, in virtue of which it is possible for certain men to conceive the idea of dedication to the highest things. The operation of this is like the breathing of the Spirit where it wills, and we have no canon of criticism or ground of explanation concerning it. It is analogous to the possession of the fairy gifts and the high gifts and the gracious gifts of the poet: we have them or have not, and their presence is as much a mystery as their absence. The law of Justice is not however involved by either alternative. In conclusion, the pillars of Justice open into one world and the pillars of the High Priestess into another.");
		tarotCardSet[4] = new TarotCard(12, "The Hanged Man", "major",
						"카드는 중단된 상태지만 생명을 상징합니다. 십자가와 매달린 자세는 깊은 의미를 갖고 있으며, 신성과 우주 사이의 관계를 나타냅니다. 생명력이 흐르는 나무와 고통이 아닌 황홀함을 표현하는 얼굴이 주목할 만합니다. 이 카드는 영광스러운 부활의 신비를 암시하며, 내면적인 각성과 변화의 가능성을 나타냅니다. 이 카드는 더 높은 본성의 이해를 통해 깨달음을 얻을 수 있는 징조입니다.",
						"The gallows from which he is suspended forms a Tau cross, while the figure--from the position of the legs--forms a fylfot cross. There is a nimbus about the head of the seeming martyr. It should be noted (1) that the tree of sacrifice is living wood, with leaves thereon; (2) that the face expresses deep entrancement, not suffering; (3) that the figure, as a whole, suggests life in suspension, but life and not death. It is a card of profound significance, but all the significance is veiled. One of his editors suggests that Éliphas Lévi did not know the meaning, which is unquestionable nor did the editor himself. It has been called falsely a card of martyrdom, a card a of prudence, a card of the Great Work, a card of duty; but we may exhaust all published interpretations and find only vanity. I will say very simply on my own part that it expresses the relation, in one of its aspects, between the Divine and the Universe.\\nHe who can understand that the story of his higher nature is imbedded in this symbolism will receive intimations concerning a great awakening that is possible, and will know that after the sacred Mystery of Death there is a glorious Mystery of Resurrection.");
		tarotCardSet[5] = new TarotCard(13, "Death", "major",
						"변화와 진전을 상징하며, 검은 기린을 탄 신비로운 기수가 나타납니다. 이 카드는 생명의 신비를 상징하는 장미와 불멸의 태양의 빛이 함께 표현됩니다. 이는 의식적인 변화와 의식의 형태 변화를 나타내며, 부활, 창조, 갱신 등의 의미가 내포되어 있습니다.",
						"The veil or mask of life is perpetuated in change, transformation and passage from lower to higher, and this is more fitly represented in the rectified Tarot by one of the apocalyptic visions than by the crude notion of the reaping skeleton. Behind it lies the whole world of ascent in the spirit. The mysterious horseman moves slowly, bearing a black banner emblazoned with the Mystic Rose, which signifies life. Between two pillars on the verge of the horizon there shines the sun of immortality. The horseman carries no visible weapon, but king and child and maiden fall before him, while a prelate with clasped hands awaits his end.\\nThere should be no need to point out that the suggestion of death which I have made in connection with the previous card is, of course, to be understood mystically, but this is not the case in the present instance. The natural transit of man to the next stage of his being either is or may be one form of his progress, but the exotic and almost unknown entrance, while still in this life, into the state of mystical death is a change in the form of consciousness and the passage into a state to which ordinary death is neither the path nor gate. The existing occult explanations of the 13th card are, on the whole, better than usual, rebirth, creation, destination, renewal, and the rest.");
		tarotCardSet[6] = new TarotCard(14, "Temperance", "major",
						"태양의 표시가 있는 날개 달린 천사를 묘사합니다. 이 카드는 내면적인 조화와 균형을 상징하며, 인류의 정신과 물질을 조화시키는 역할을 나타냅니다. 한 발은 땅 위에, 한 발은 물 위에 있어 본질의 성질을 상징합니다. 이 카드는 전통적인 의미를 넘어서 내면의 평온과 영적인 성장의 가능성을 암시합니다.",
						"A winged angel, with the sign of the sun upon his forehead and on his breast the square and triangle of the septenary. I speak of him in the masculine sense, but the figure is neither male nor female. It is held to be pouring the essences of life from chalice to chalice. It has one foot upon the earth and one upon waters, thus illustrating the nature of the essences. A direct path goes up to certain heights on the verge of the horizon, and above there is a great light, through which a crown is seen vaguely. Hereof is some part of the Secret of Eternal Life, as it is possible to man in his incarnation. All the conventional emblems are renounced herein.\\nSo also are the conventional meanings, which refer to changes in the seasons, perpetual movement of life and even the combination of ideas. It is, moreover, untrue to say that the figure symbolizes the genius of the sun, though it is the analogy of solar light, realized in the third part of our human triplicity. It is called Temperance fantastically, because, when the rule of it obtains in our consciousness, it tempers, combines and harmonises the psychic and material natures. Under that rule we know in our rational part something of whence we came and whither we are going.");
		tarotCardSet[7] = new TarotCard(15, "The Devil", "major",
						"우리의 낮은 욕구, 물질적인 삶의 사슬, 그리고 자유를 위한 싸움을 상징합니다. 이 카드는 과도한 욕망이나 중독에 대한 통제 감각을 잃어가는 상황을 나타냅니다. 그러나 이는 영원한 노예 상태를 의미하는 것은 아니며, 그것은 우리의 '동물적 본성'이 우리를 지배하도록 허용하는 선택에 대한 상징일 뿐입니다.",
						"The design is an accommodation, mean or harmony, between several motives mentioned in the first part. The Horned Goat of Mendes, with wings like those of a bat, is standing on an altar. At the pit of the stomach there is the sign of Mercury. The right hand is upraised and extended, being the reverse of that benediction which is given by the Hierophant in the fifth card. In the left hand there is a great flaming torch, inverted towards the earth. A reversed pentagram is on the forehead. There is a ring in front of the altar, from which two chains are carried to the necks of two figures, male and female. These are analogous with those of the fifth card, as if Adam and Eve after the Fall. Hereof is the chain and fatality of the material life.\\nThe figures are tailed, to signify the animal nature, but there is human intelligence in the faces, and he who is exalted above them is not to be their master for ever. Even now, he is also a bondsman, sustained by the evil that is in him and blind to the liberty of service. With more than his usual derision for the arts which he pretended to respect and interpret as a master therein, Éliphas Lévi affirms that the Baphometic figure is occult science and magic. Another commentator says that in the Divine world it signifies predestination, but there is no correspondence in that world with the things which below are of the brute. What it does signify is the Dweller on the Threshold without the Mystical Garden when those are driven forth therefrom who have eaten the forbidden fruit.");
		tarotCardSet[8] = new TarotCard(16, "The Tower", "major",
						"강렬하게 변화와 해방을 상징합니다. 이는 고정관념이나 거짓된 이해가 붕괴되는 것을 나타냅니다. 이 카드는 때로는 자만이나 오만함의 벌을 상징하기도 합니다. 물질적이거나 동물적 상태로의 추락과 지적인 면에서의 파괴를 의미할 수 있습니다. 깊게 보면, 세상의 특정 단계나 체제의 종말을 나타내기도 합니다.",
						"Occult explanations attached to this card are meagre and mostly disconcerting. It is idle to indicate that it depicts min in all its aspects, because it bears this evidence on the surface. It is said further that it contains the first allusion to a material building, but I do not conceive that the Tower is more or less material than the pillars which we have met with in three previous cases. I see nothing to warrant Papus in supposing that it is literally the fall of Adam, but there is more in favour of his alternative--that it signifies the materialization of the spiritual word. The bibliographer Christian imagines that it is the downfall of the mind, seeking to penetrate the mystery of God. I agree rather with Grand Orient that it is the ruin of the House of We, when evil has prevailed therein, and above all that it is the rending of a House of Doctrine. I understand that the reference is, however, to a House of Falsehood. It illustrates also in the most comprehensive way the old truth that \\\"except the Lord build the house, they labour in vain that build it.\\\"\\nThere is a sense in which the catastrophe is a reflection from the previous card, but not on the side of the symbolism which I have tried to indicate therein. It is more correctly a question of analogy; one is concerned with the fall into the material and animal state, while the other signifies destruction on the intellectual side. The Tower has been spoken of as the chastisement of pride and the intellect overwhelmed in the attempt to penetrate the Mystery of God; but in neither case do these explanations account for the two persons who are the living sufferers. The one is the literal word made void and the other its false interpretation. In yet a deeper sense, it may signify also the end of a dispensation, but there is no possibility here for the consideration of this involved question.");
		tarotCardSet[9] = new TarotCard(19, "The Sun", "major",
						"초월적인 빛과 인류의 진보를 상징합니다. 아이가 말 위에 타고 붉은 기를 들고 있는 모습은 순수함과 지혜를 나타냅니다. 이 카드는 우리의 본성을 이끌며 새로운 정신적인 성장을 경험하는 시기를 상징합니다. \"태양\" 카드는 단순하고 순수한 마음으로 인류의 진보와 회복된 세계를 표현합니다. 이 카드는 자아를 알고 영혼의 깨달음을 통해 동물적 본성을 조화롭게 이끌어내는 시기를 상징합니다.",
						"The naked child mounted on a white horse and displaying a red standard has been mentioned already as the better symbolism connected with this card. It is the destiny of the Supernatural East and the great and holy light which goes before the endless procession of humanity, coming out from the walled garden of the sensitive life and passing on the journey home. The card signifies, therefore, the transit from the manifest light of this world, represented by the glorious sun of earth, to the light of the world to come, which goes before aspiration and is typified by the heart of a child.\\nBut the last allusion is again the key to a different form or aspect of the symbolism. The sun is that of consciousness in the spirit - the direct as the antithesis of the reflected light. The characteristic type of humanity has become a little child therein--a child in the sense of simplicity and innocence in the sense of wisdom. In that simplicity, he bears the seal of Nature and of Art; in that innocence, he signifies the restored world. When the self-knowing spirit has dawned in the consciousness above the natural mind, that mind in its renewal leads forth the animal nature in a state of perfect conformity.");
		tarotCardSet[10] = new TarotCard(20, "Judegement", "major",
						"초월적인 부름에 대한 응답으로 내면적인 변화와 영원한 생명을 상징합니다. 큰 천사가 트럼펫을 불며 죽은 자들이 일어나는 모습이 그려져 있습니다. 이 카드는 내면의 변화와 순간적인 부활을 나타내며, 영원한 삶의 업적을 달성하는 순간을 상징합니다. \"심판\" 카드는 내면적 깨달음과 균형을 나타내며, \"Temperance\" 카드와 유사한 의미를 가지고 있습니다.",
						"I have said that this symbol is essentially invariable in all Tarot sets, or at least the variations do not alter its character. The great angel is here encompassed by clouds, but he blows his bannered trumpet, and the cross as usual is displayed on the banner. The dead are rising from their tombs--a woman on the right, a man on the left hand, and between them their child, whose back is turned. But in this card there are more than three who are restored, and it has been thought worth while to make this variation as illustrating the insufficiency of current explanations. It should be noted that all the figures are as one in the wonder, adoration and ecstacy expressed by their attitudes. It is the card which registers the accomplishment of the great work of transformation in answer to the summons of the Supernal--which summons is heard and answered from within.\\nHerein is the intimation of a significance which cannot well be carried further in the present place. What is that within us which does sound a trumpet and all that is lower in our nature rises in response--almost in a moment, almost in the twinkling of an eye? Let the card continue to depict, for those who can see no further, the Last judgment and the resurrection in the natural body; but let those who have inward eyes look and discover therewith. They will understand that it has been called truly in the past a card of eternal life, and for this reason it may be compared with that which passes under the name of Temperance.");
		tarotCardSet[11] = new TarotCard(21, "The World", "major",
						"이 카드는 우주의 완성과 종말, 그리고 신의 시각을 인식한 영혼의 상태를 상징합니다. 이것은 본질적으로 세상이 가장 완벽한 상태로 복원됐을 때의 상태를 의미하며, 특히 모든 것이 좋게 선언된 과거의 시점을 이야기합니다. 마지막으로, 이 카드는 마법사의 왕관으로 여겨지기도 합니다.",
						"As this final message of the Major Trumps is unchanged--and indeed unchangeable--in respect of its design, it has been partly described already regarding its deeper sense. It represents also the perfection and end of the Cosmos, the secret which is within it, the rapture of the universe when it understands itself in God. It is further the state of the soul in the consciousness of Divine Vision, reflected from the self-knowing spirit. But these meanings are without prejudice to that which I have said concerning it on the material side.\\nIt has more than one message on the macrocosmic side and is, for example, the state of the restored world when the law of manifestation shall have been carried to the highest degree of natural perfection. But it is perhaps more especially a story of the past, referring to that day when all was declared to be good, when the morning stars sang together and all the Sons of God shouted for joy. One of the worst explanations concerning it is that the figure symbolizes the Magus when he has reached the highest degree of initiation; another account says that it represents the absolute, which is ridiculous. The figure has been said to stand for Truth, which is, however, more properly allocated to the seventeenth card. Lastly, it has been called the Crown of the Magi.");
		tarotCardSet[12] = new TarotCard(29, "Eight of Cups", "cups",
						"일시적인 만족을 떠나고 새로운 방향을 찾는 의미를 가지고 있습니다. 이 카드는 어떤 문제나 상황에 대한 감소, 중요성 감소, 또는 사소한 결과를 나타낼 수 있습니다. 주인공은 자신의 행복이나 이전의 관심사를 떠나며, 새로운 여정을 시작하는 모습입니다. 이 카드는 삶의 변화와 내적 성장을 상징하며, 현재의 상황에서 벗어나 새로운 가능성을 모색하고자 하는 욕구를 나타냅니다.",
						"The card speaks for itself on the surface, but other readings are entirely antithetical--giving joy, mildness, timidity, honour, modesty. In practice, it is usually found that the card shews the decline of a matter, or that a matter which has been thought to be important is really of slight consequence--either for good or evil.;A man of dejected aspect is deserting the cups of his felicity, enterprise, undertaking or previous concern.");
		tarotCardSet[13] = new TarotCard(40, "Five of Wands", "wands",
						"이 카드는 모방과 경쟁을 상징합니다. 가짜 싸움과 같은 모방 전투를 나타내며, 부와 행운을 찾아 열심히 경쟁하고 투쟁하는 모습을 보여줍니다. 이 카드는 인생의 전투와 관련이 있으며, 금, 이익, 풍요로움을 나타낼 수도 있습니다. 이는 또한 젊은이들이 지팡이를 휘두르며 모방 전투를 벌이는 모습을 보여줍니다.",
						"Imitation, as, for example, sham fight, but also the strenuous competition and struggle of the search after riches and fortune. In this sense it connects with the battle of life. Hence some attributions say that it is a card of gold, gain, opulence.;A posse of youths, who are brandishing staves, as if in sport or strife. It is mimic warfare, and hereto correspond the");
		tarotCardSet[14] = new TarotCard(43, "Eight of Wands", "wands",
						"이 카드는 활동과 역동성을 상징하며, 목표를 향한 신속한 진행과 성공을 암시합니다. 그것은 희망과 기대감이 크고 빠른 속도로 행복한 결과에 다가가는 것을 나타냅니다. 이 카드는 또한 움직임과 전진을 상징하며, 사랑의 화살도 표현할 수 있습니다.",
						"Activity in undertakings, the path of such activity, swiftness, as that of an express messenger; great haste, great hope, speed towards an end which promises assured felicity; generally, that which is on the move; also the arrows of love.;The card represents motion through the immovable-a flight of wands through an open country; but they draw to the term of their course. That which they signify is at hand; it may be even on the threshold.");
		tarotCardSet[15] = new TarotCard(65, "Two of Swords", "swords",
						"순응과 균형, 용기, 우정, 군사적인 조화를 상징합니다. 또한, 애정, 애착, 친밀함과 같은 의미도 전할 수 있습니다. 그러나 검 카드는 일반적으로 인간 사회에서 긍정적인 힘을 상징하지 않기 때문에 조화와 유리한 해석은 조심스럽게 고려되어야 합니다. 카드에는 눈가리개를 쓴 여성이 어깨 위에 검을 균형있게 놓고 있는 모습이 그려져 있습니다.",
						"Conformity and the equipoise which it suggests, courage, friendship, concord in a state of arms; another reading gives tenderness, affection, intimacy. The suggestion of harmony and other favourable readings must be considered in a qualified manner, as Swords generally are not symbolical of beneficent forces in human affairs.;A hoodwinked female figure balances two swords upon her shoulders.");
	}

	public static TarotCardSetSingleton getInstance() {
		return standard;
	}

	public TarotCard getTarotCard(int index) {
		return tarotCardSet[index - 1];
	}

	public TarotCard findTarotCardByNumber(int number) {
		Optional<TarotCard> foundCard = Arrays.stream(tarotCardSet)
						.filter(card -> card.getNumber() == number)
						.findFirst();

		if (foundCard.isPresent()) {
			return foundCard.get();
		} else {
			throw new IllegalArgumentException("No such card with number " + number);
		}
	}
}
