spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    url: ${MYSQL_DATABASE_URL}
    #    username: ${MYSQL_DATABASE_USERNAME}
    #    password: ${MYSQL_DATABASE_PASSWORD}
    url: jdbc:mysql://localhost:3306/talog
    username: root
    password: anso33

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080